# Copyright 2018 The GO2S Authors. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.

default:
	go run makestatic.go

clean:
	-rm static.go
