// Copyright 2018 The GO2S Authors. All rights reserved.
// Use of this source code is governed by a Apache license
// that can be found in the LICENSE file.

// Code generated by "makestatic"; DO NOT EDIT.

package tpl

var Files = map[string]string{
	"layout.html": `{{ define "layout" }}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
{{if .cfg.Favicon}}
    <link rel="icon" href="{{.cfg.Favicon}}">{{end}}
    <title>Login</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <script src="//code.jquery.com/jquery-2.2.4.min.js"></script>
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
<div class="container">
    <div>
    {{if .cfg.Logo}}<img src="{{.cfg.Logo}}"/>{{end}}
    {{if .cfg.ServerName}}<h1>{{.cfg.ServerName}}</h1>{{end}}
    </div>
{{ template "content" . }}
</div>
</body>
</html>
{{ template "script" . }}
{{ end }}`,

	"auth.html": `{{ define "content" }}
<div class="jumbotron">
    <form method="POST">
        <h1>Authorize</h1>
        <p>The client
            <b>{{ .client}}</b> would like to perform actions on your behalf.</p>
        <p class=".text-center">
        <h3>{{ .scope}}</h3></p>
        <p>
            <button type="submit" class="btn btn-primary btn-lg" style="width:200px;">Allow</button>
        </p>
    </form>
</div>
{{ end }}

{{ define "script" }}
{{ end }}`,

	"index.html": `{{ define "content" }}
Welcome, {{.user_id}}!
{{ end }}

{{ define "script" }}
{{ end }}`,

	"login.html": `{{ define "content" }}
<form id="login_form" method="POST">
    <div class="form-group">
        <label for="username">User Name</label>
        <input type="text" class="form-control" name="username" placeholder="Please enter your user name">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" name="password" placeholder="Please enter your password">
    </div>
    <button type="submit" class="btn btn-success">Login</button>
</form>
{{ end }}

{{ define "script" }}
<script>
    function getQueryString() {
        var result = {};
        if (!window.location.search.length) return result;
        var qs = window.location.search.slice(1);
        var parts = qs.split("&");
        for (var i = 0, len = parts.length; i < len; i++) {
            var tokens = parts[i].split("=");
            result[tokens[0]] = decodeURIComponent(tokens[1]);
        }
        return result;
    }

    $(document).ready(function () {
        var form = $("#login_form");
        form.action = [location.protocol, '//', location.host, location.pathname].join('');
        form.submit(function (e) {
            var qs = getQueryString();
            for (var key in qs) {
                if (key == "redirect_uri" || key == "client_id" || key == "response_type" || key == "state" || key == "scope") {
                    var field = $(document.createElement("input"));
                    field.attr("name", key).attr("type", "hidden");
                    field.val(qs[key]);
                    $(this).append(field);
                }
            }
        });
    });
</script>
{{ end }}`,
}
